### ISSUE TITLE
No clamping happening when inside a flex container

### ISSUE THREAD

**Issue by derochedesign** [drenther/use-clamp-text#2]
Is there some style stipulation (like a defined width) for the container that holds the text element? I have an `<h1>` inside of a flex container and the resulting output of `clampedText` is just "...". If I remove the `display:flex` on all the parent containers it seems to work (but of course that isn't an option for me).

**Comment by drenther** [comment]
Can you create a minimal reproduction for it on codesandbox and share?

**Comment by radomir-radionov** [comment]
I have created a new app with creat-react-app and try to use your package and  as a result I have a  word "Truncated" and "." on the screen. There are no styles.
