### ISSUE TITLE
Any chance this can support SSR?

### ISSUE THREAD

**Issue by khalilp5** [drenther/use-clamp-text#3]
I am using this package with Next JS and I am having a hard time rendering this correctly on the server. Any way I can achieve that? I tried using window type and it throws a hydration error.

**Comment by drenther** [comment]
Can you please share a codesandbox link that reproduces the error?

**Comment by khalilp5** [comment]
Hey,

Here you go: [link](https://codesandbox.io/p/sandbox/wonderful-cloud-5dkhhk)

I have integrated the Hook in Next JS. Once you open the app and disable javascript the text defaults to "."

![image](https://github.com/drenther/use-clamp-text/assets/105921857/eb0de9b0-a20c-4b61-adf6-2e2d36b5ce53)

**Comment by drenther** [comment]
There is no hydration error showing up on your codesandbox as you mentioned in the original issue.

Regarding the second comment - `.` is essential to how the correct computed lineHeight is detected and hence that must be the first string that is rendered in the node

**Comment by khalilp5** [comment]
I understand that but how do I show the actual text in the server before the client is hydrated?

**Comment by drenther** [comment]
You can render the plain text for first render and post that mount a component that handles the clamping.

Here's an [example](https://codesandbox.io/p/sandbox/use-clamped-text-ssr-trick-k7thyp?file=/pages/index.js)
